name: Monthly Data Download

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the first day of every month
  workflow_dispatch:  # Allows for manual triggering of the workflow

jobs:
  download_and_process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      run: |
        install.packages(c("tidyverse", "janitor", "arrow"), repos = "https://cloud.r-project.org")
        # Add any other packages your script needs here

    - name: Run download script
      run: Rscript download_files.R
